@Feed.Generator_HostAddress = http://localhost:5023

GET {{Feed.Generator_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{Feed.Generator_HostAddress}}/weatherreport/
Accept: application/json

###
