apiVersion: v1
kind: Service
metadata:
  name: feed-ingester
spec:
  type: LoadBalancer
  selector:
    app: feed-ingester
  ports:
  - port: 5227
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-ingester
spec:
  selector:
    matchLabels:
      app: feed-ingester
  template:
    metadata:
      labels:
        app: feed-ingester
    spec:
      containers:
      - name: feed-ingester
        image: mak100186/feed-ingester:1.0.3
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080