<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Confluent.Kafka" />
    <PackageReference Include="Aspire.StackExchange.Redis.OutputCaching" />
    <PackageReference Include="ClrHeapAllocationAnalyzer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Analyzers" />
    <PackageReference Include="SonarAnalyzer.CSharp">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Linq.Async" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Constants\Constants.csproj" />
    <ProjectReference Include="..\Models\Models.csproj" />
  </ItemGroup>

</Project>
